version: '2'

networks:
  net_substra:
    external: true

services:

  rca-org3:
    container_name: rca-org3
    image: substra/fabric-ca
    command: /bin/bash -c 'python3 /scripts/start-root-ca.py 2>&1 | tee /data/logs/rca-org3.log; sleep 99999'
    ports:
      - "11054:7054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - TARGET_CERTFILE=/data/orgs/org3/
    volumes:
      - ./python-scripts:/scripts
      - ./data:/data
      - ./conf/org3/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    networks:
      - net_substra

  setupOrg3:
    container_name: setupOrg3
    image: substra/fabric-ca-tools
    # image: substra/fabric-ca-tools-debug
    command: /bin/bash -c 'python3 /scripts/setupOrg3.py 2>&1 | tee /data/logs/setup.log; sleep 99999'
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CFG_PATH=/data
        # - PYTHONPATH=$PYTHONPATH:/fabric-sdk-py
    volumes:
      - ./data:/data
      - ./conf:/conf
      - ./python-scripts:/scripts
      - ./conf/org3/fabric-ca-client-config.yaml:/root/cas/rca-org3/fabric-ca-client-config.yaml
      - ./network-test/config_files/configtx.yaml:/data/configtx.yaml
      - ./network-test/add-org.sh:/add-org.sh

      # - ../../fabric-sdk-py:/fabric-sdk-py # for debugging with fabric-ca-tools-debug
    networks:
      - net_substra
    depends_on:
      - rca-org3

  peer1-org3:
    container_name: peer1-org3
    image: substra/fabric-ca-peer
    environment:
      - ORG=org3
      - PEER_INDEX=0
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'python3 /scripts/start-peerOrg3.py 2>&1 | tee /data/logs/peer1-org3.log; sleep 99999'
    ports:
      - 11051:7051
      - 11053:7053
    volumes:
      - ./data:/data
      - /var/run:/host/var/run
      - ./python-scripts:/scripts
      - ./conf/org3/fabric-ca-client-config.yaml:/opt/gopath/src/github.com/hyperledger/fabric/peer/fabric-ca-client-config.yaml
      - ./conf/org3/peer1/core.yaml:/etc/hyperledger/fabric/core.yaml
    networks:
      - net_substra
    depends_on:
      - setupOrg3

  peer2-org3:
    container_name: peer2-org3
    image: substra/fabric-ca-peer
    environment:
      - ORG=org3
      - PEER_INDEX=1
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'python3 /scripts/start-peerOrg3.py 2>&1 | tee /data/logs/peer2-org3.log; sleep 99999'
    ports:
      - 12051:7051
      - 12053:7053
    volumes:
      - ./data:/data
      - /var/run:/host/var/run
      - ./python-scripts:/scripts
      - ./conf/org3/fabric-ca-client-config.yaml:/opt/gopath/src/github.com/hyperledger/fabric/peer/fabric-ca-client-config.yaml
      - ./conf/org3/peer2/core.yaml:/etc/hyperledger/fabric/core.yaml
    networks:
      - net_substra
    depends_on:
      - setupOrg3

  runOrg3:
    container_name: runOrg3
    image: substra/fabric-ca-tools
    environment:
      - GOPATH=/opt/gopath
    command: /bin/bash -c 'sleep 3;python3 /scripts/runOrg3.py 2>&1 | tee /data/logs/runOrg3.log; sleep 99999'
    volumes:
      - ./python-scripts:/scripts
      - ./data:/data
      - ../substra-chaincode/chaincode:/opt/gopath/src/github.com/hyperledger/chaincode
      - ./conf:/conf

    networks:
      - net_substra
