apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kubectl
    image: google/cloud-sdk
    command: [cat]
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 256Mi
