apiVersion: v1
kind: Pod
spec:
  containers:
    - name: helm
      image: dtzar/helm-kubectl
      command: [cat]
      tty: true
      volumeMounts:
        - name: chartmuseum-secret
          mountPath: /secret
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/chartmuseum-secret.json
      resources:
        requests:
          cpu: 1
          memory: 128Mi
        limits:
          cpu: 1
          memory: 512Mi
  volumes:
    - name: chartmuseum-secret
      secret:
        secretName: chartmuseum-secret
