apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python
    image: python:3.7
    command: [cat]
    tty: true
    env:
    - name: SUBSTRA_PATH
      value: "/tmp/substra"
    - name: SUBSTRA_CHAINCODE_PATH
      value: "/tmp/substra/substra-chaincode"
    - name: MY_HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    volumeMounts:
      - { name: substra, mountPath: /tmp/substra }
      - { name: docker, mountPath: /var/run/docker.sock }
    resources:
      requests:
        cpu: 1
        memory: 256Mi
      limits:
        cpu: 2
        memory: 1024Mi
  volumes:
    - name: substra
      hostPath: { path: /tmp/substra, type: DirectoryOrCreate }
    - name: docker
      hostPath: { path: /var/run/docker.sock, type: File }
