apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python
    image: python:3.7
    command: [cat]
    tty: true
    env:
    - name: SUBSTRA_PATH
      value: "/tmp/substra"
    volumeMounts:
      - { name: substra, mountPath: /tmp/substra }
      - { name: docker, mountPath: /var/run/docker.sock }
    resources:
      requests:
        cpu: 100m
        memory: 2048Mi
      limits:
        cpu: 2
        memory: 4096Mi
  volumes:
    - name: substra
      hostPath: { path: /tmp/substra, type: DirectoryOrCreate }
    - name: docker
      hostPath: { path: /var/run/docker.sock, type: File }
