apiVersion: v1
kind: Pod
spec:
  containers:
    - name: build
      image: google/cloud-sdk:alpine
      command: [cat]
      tty: true
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret
      resources:
        requests:
          cpu: 1
          memory: 128Mi
        limits:
          cpu: 1
          memory: 512Mi
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
