version: '2'

networks:
  net_substra:
    external: true

services:
    peer1-chu-nantes:
        command: python3 start-peer.py 2>&1
        container_name: peer1-chu-nantes
        depends_on:
        - setup-add
        environment:
        - GODEBUG=netdns=go+1
        - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric/
        image: substra/substra-ca-peer
        logging:
            driver: json-file
            options:
                max-file: '5'
                max-size: 20m
        networks:
        - substra
        ports:
        - 9051:7051
        - 9053:7053
        restart: unless-stopped
        volumes:
        - /substra/data:/substra/data
        - /substra/conf/chu-nantes/peer1/conf.json:/substra/conf/conf.json
        - /substra/backup/orgs/chu-nantes/peer1/:/var/hyperledger/production/
        - ./python-scripts/util.py:/etc/hyperledger/util.py
        - /var/run/docker.sock:/host/var/run/docker.sock
        - /substra/conf/chu-nantes/fabric-ca-client-config.yaml:/etc/hyperledger/fabric/fabric-ca-client-config.yaml
        - /substra/conf/chu-nantes/peer1/core.yaml:/etc/hyperledger/fabric/core.yaml
        working_dir: /etc/hyperledger/
    peer2-chu-nantes:
        command: python3 start-peer.py 2>&1
        container_name: peer2-chu-nantes
        depends_on:
        - setup-add
        environment:
        - GODEBUG=netdns=go+1
        - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric/
        image: substra/substra-ca-peer
        logging:
            driver: json-file
            options:
                max-file: '5'
                max-size: 20m
        networks:
        - substra
        ports:
        - 10051:7051
        - 10053:7053
        restart: unless-stopped
        volumes:
        - /substra/data:/substra/data
        - /substra/conf/chu-nantes/peer2/conf.json:/substra/conf/conf.json
        - /substra/backup/orgs/chu-nantes/peer2/:/var/hyperledger/production/
        - ./python-scripts/util.py:/etc/hyperledger/util.py
        - /var/run/docker.sock:/host/var/run/docker.sock
        - /substra/conf/chu-nantes/fabric-ca-client-config.yaml:/etc/hyperledger/fabric/fabric-ca-client-config.yaml
        - /substra/conf/chu-nantes/peer2/core.yaml:/etc/hyperledger/fabric/core.yaml
        working_dir: /etc/hyperledger/
    rca-chu-nantes:
        command: /bin/bash -c "fabric-ca-server start 2>&1"
        container_name: rca-chu-nantes
        environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        image: substra/substra-ca
        logging:
            driver: json-file
            options:
                max-file: '5'
                max-size: 20m
        networks:
        - substra
        ports:
        - 8054:7054
        restart: unless-stopped
        volumes:
        - /substra/data:/substra/data
        - /substra/backup/orgs/chu-nantes/rca:/etc/hyperledger/fabric-ca-server/
        - /substra/conf/chu-nantes/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
        working_dir: /etc/hyperledger/
    run-add:
        command: /bin/bash -c "set -o pipefail;sleep 3;python3 /scripts/run-add.py 2>&1
            | tee /substra/data/log/run.log"
        container_name: run
        depends_on:
        - peer1-chu-nantes
        - peer2-chu-nantes
        environment:
        - GOPATH=/opt/gopath
        image: substra/substra-ca-tools
        networks:
        - substra
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /substra/data:/substra/data
        - /substra/conf:/substra/conf
        - ./python-scripts:/scripts
        - ../substra-chaincode/chaincode:/opt/gopath/src/github.com/hyperledger/chaincode
    setup-add:
        command: /bin/bash -c "set -o pipefail;python3 /scripts/setup-add.py 2>&1 | tee
            /substra/data/log/setup.log"
        container_name: setup
        depends_on:
        - rca-chu-nantes
        environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CFG_PATH=/substra/data
        image: substra/substra-ca-tools
        networks:
        - substra
        volumes:
        - /substra/data:/substra/data
        - ./python-scripts:/scripts
        - /substra/conf/conf.json:/substra/conf/conf.json
        - /substra/conf/orderer/fabric-ca-client-config.yaml:/root/cas/rca-orderer/fabric-ca-client-config.yaml
        - /substra/conf/owkin/fabric-ca-client-config.yaml:/root/cas/rca-owkin/fabric-ca-client-config.yaml
        - /substra/conf/chu-nantes/fabric-ca-client-config.yaml:/root/cas/rca-chu-nantes/fabric-ca-client-config.yaml
