# Copyright 2018 Owkin, inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- range $index, $value := .Values.fetchSecrets }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s-fetch-secret-%d" $.Release.Name $.Chart.Name $index | lower | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ printf "%s-fetch-secret-%d" $.Chart.Name $index | lower | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/part-of: {{ $.Release.Name | lower | trunc 63 | trimSuffix "-" }}
spec:
  template:
    spec:
      dnsPolicy: {{ $.Values.dnsPolicy }}
      {{- if or $.Values.image.pullSecretsInline $.Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $index, $value := $.Values.image.pullSecretsInline }}
        - name: {{ template "substra.fullname" $ }}-pull-secret-{{ $index }}
      {{- end }}
      {{- range $.Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "substra.fullname" $ }}
      containers:
      - name: fabric-tools
        image: google/cloud-sdk:latest
        command: ['sh', '-c']
        args:
          - |
            until kubectl -n {{ .namespace }} get secret {{ .from }} 1>/dev/null 2>/dev/null
            do
              echo "\033[0;31m Secret {{ .from }} not found on namespace {{ .namespace }} \033[0m"
              sleep 3
            done

            kubectl -n {{ .namespace }} get secret {{ .from }} -o jsonpath="{.data.{{ .filename | replace "." "\\." }}}" | \
              base64 -d | \
              kubectl create secret generic {{ .to }} --from-file={{ .filename }}=/dev/stdin
    {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
